services:
  kf-payment:
    image: kf-payment:latest
    volumes:
      - ./prod/config.yaml:/app/config.yaml
    command:
      - /app/app
    ports:
      - "8084:808"
    restart: always
    environment:
      CONFIG_FILE: '/app/config.yaml'
    networks:
      - kf_network

networks:
  kf_network:
    external: true
